VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
OLED_ENABLE = no
OLED_DRIVER = SSD1306
EXTRAKEY_ENABLE = no
COMBO_ENABLE = no
QMK_SETTINGS = no
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
